REM
REM CREATE_MRG_TARGET_ERRLOG
REM

REM
REM Create an error log for the table
REM

DROP TABLE MRG_TARGET_ERRLOG;
BEGIN
  DBMS_ERRLOG.CREATE_ERROR_LOG (
        DML_TABLE_NAME      => 'MRG_TARGET'
      , ERR_LOG_TABLE_NAME  => 'MRG_TARGET_ERRLOG'
      , ERR_LOG_TABLE_OWNER => USER
      , ERR_LOG_TABLE_SPACE => 'USERS'
    );
END;
/
