REM
REM CREATE_TABLE_EXCEPTION_MSGS.SQL
REM

REM
REM A table to store exceptions
REM

DROP   TABLE EXCEPTION_MSGS;
CREATE TABLE EXCEPTION_MSGS (
     ERROR_ID NUMBER
   , MESSAGE1 VARCHAR2(200)    
   , MESSAGE2 VARCHAR2(200)
  );
